# Generated by Django 3.1.2 on 2020-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201107_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('washer', 'washer'), ('dryer', 'dryer')], max_length=10),
        ),
    ]
