# Generated by Django 3.1.2 on 2020-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201107_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='LF',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('lost', 'lost'), ('job', 'job')], default='lost', max_length=10),
        ),
    ]
