# Generated by Django 3.1.2 on 2020-11-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201107_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='JMABG',
            new_name='JMBAG',
        ),
    ]
