# Generated by Django 3.1.2 on 2020-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_user_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recension',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='employee',
            new_name='posted_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
