# Generated by Django 3.1.2 on 2020-12-11 15:45

import common.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20201210_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('pause_start', models.TimeField()),
                ('pause_end', models.TimeField()),
                ('wash_price', models.FloatField()),
                ('drying_price', models.FloatField()),
            ],
            options={
                'ordering': ['-date_changed'],
            },
        ),
        migrations.DeleteModel(
            name='WashDay',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='basket_taken',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_worked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=common.models.IntegerRangeField(),
        ),
    ]
