# Generated by Django 3.1.2 on 2020-12-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20201213_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='start',
        ),
    ]
