# Generated by Django 3.1.2 on 2020-12-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20201214_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cart_number',
            new_name='card_number',
        ),
    ]
