# Generated by Django 3.1.2 on 2020-12-14 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20201214_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.card'),
        ),
    ]
