# Generated by Django 3.1.2 on 2020-12-19 11:39

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20201214_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='missed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='date_changed',
            field=models.DateTimeField(blank=True, default=common.models.return_date_changed),
        ),
    ]
