# Generated by Django 3.1.2 on 2020-12-20 20:26

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20201219_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='JMBAG',
            field=models.CharField(default=common.models.random_string, max_length=10, unique=True),
        ),
    ]
