# Generated by Django 3.1.2 on 2020-12-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20201220_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='first_shift_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundry',
            name='middle',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='pause2_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundry',
            name='pause2_start',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='second_shift_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
