# Generated by Django 3.1.2 on 2020-12-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20201223_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='pause2_start',
            field=models.TimeField(),
        ),
    ]
