# Generated by Django 3.1.2 on 2020-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20201223_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='baskets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
